/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CelebrationsAdminRole;

import Model.PSH_Business;

/**
 *
 * @author keerthanajagana
 */
public class PSH_CelebrationPlannerAdminJPanel extends javax.swing.JPanel {

    PSH_Business business;
    private Runnable callMethod1;
    private Runnable callMethod2;
    private Runnable callMethod3;
    private Runnable callMethod4;
    /**
     * Creates new form PSH_CelebrationPlannerAdminJPanel
     */
    public PSH_CelebrationPlannerAdminJPanel(PSH_Business business, Runnable callMethod1, Runnable callMethod2, Runnable callMethod3, Runnable callMethod4) {
        initComponents();
        this.business=business;
        this.callMethod1 = callMethod1;
        this.callMethod2 = callMethod2;
        this.callMethod3 = callMethod3;
        this.callMethod4 = callMethod4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationBtn = new javax.swing.JButton();
        entCatBtn = new javax.swing.JButton();
        entManagerBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        locationBtn.setText("Locations");
        locationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBtnActionPerformed(evt);
            }
        });

        entCatBtn.setText("Enterprise Catalogue");
        entCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCatBtnActionPerformed(evt);
            }
        });

        entManagerBtn.setText("Enterprise Manager");
        entManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entManagerBtnActionPerformed(evt);
            }
        });

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Celebration Planner Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(locationBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(entCatBtn)))
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(entManagerBtn)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(customerBtn)
                        .addGap(207, 207, 207))))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(locationBtn)
                .addGap(46, 46, 46)
                .addComponent(entCatBtn)
                .addGap(51, 51, 51)
                .addComponent(entManagerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(customerBtn)
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBtnActionPerformed
        // TODO add your handling code here:
        callMethod1.run();
    }//GEN-LAST:event_locationBtnActionPerformed

    private void entCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCatBtnActionPerformed
        // TODO add your handling code here:
        callMethod2.run();
    }//GEN-LAST:event_entCatBtnActionPerformed

    private void entManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entManagerBtnActionPerformed
        // TODO add your handling code here:
        callMethod3.run();
    }//GEN-LAST:event_entManagerBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        callMethod4.run();
    }//GEN-LAST:event_customerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton entCatBtn;
    private javax.swing.JButton entManagerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton locationBtn;
    // End of variables declaration//GEN-END:variables
}
