/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CelebrationsAdminRole;
import Model.PSH_Business;
import Model.PSH_location;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keerthanajagana
 */
public class PSH_LocationsJPanel extends javax.swing.JPanel {

    private PSH_Business enterpriseAdmin;
    private Runnable callOnCreateMethod;
    /**
     * Creates new form PSH_LocationsJPanel
     */
    public PSH_LocationsJPanel(PSH_Business enterpriseAdmin,Runnable callOnCreateMethod) {
        this.callOnCreateMethod=callOnCreateMethod;
        this.enterpriseAdmin = enterpriseAdmin;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bacjBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        locTable = new javax.swing.JTable();
        addLOcBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bacjBtn.setText("Back");
        bacjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacjBtnActionPerformed(evt);
            }
        });
        add(bacjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 80, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Locations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 156, 50, 20));

        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 90, -1));

        locTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Location Name"
            }
        ));
        jScrollPane1.setViewportView(locTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        addLOcBtn.setText("ADD");
        addLOcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLOcBtnActionPerformed(evt);
            }
        });
        add(addLOcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bacjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacjBtnActionPerformed
        // TODO add your handling code here:
        callOnCreateMethod.run();
    }//GEN-LAST:event_bacjBtnActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locActionPerformed

    public boolean validateName() {
        if (loc.getText().matches("[a-zA-Z]{2,19}")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Invalid input: name should contain only alphabets");
            return false;
        }
    }
    private void addLOcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLOcBtnActionPerformed
        // TODO add your handling code here:
        String name = loc.getText();
        if (validateName()) {
            enterpriseAdmin.addLocation(name);
            JOptionPane.showMessageDialog(this, "Location added !!");
            loc.setText("");
            populateTable();
        }
    }//GEN-LAST:event_addLOcBtnActionPerformed
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) locTable.getModel();
        model.setRowCount(0);
        Object row[] = new Object[10];
        for (PSH_location location : enterpriseAdmin.getListOfLocation()) {        //populate location
            row[0] = location.getName();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLOcBtn;
    private javax.swing.JButton bacjBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loc;
    private javax.swing.JTable locTable;
    // End of variables declaration//GEN-END:variables
}
